In [1]:
import string    
import random 
import numpy as np
S = 16
s1 = ''.join(random.choices(string.ascii_uppercase, k = S))   
ran1 = str(s1)
print("First String: ",s1)  

First String:  LLOZPTHYNVYXIPUY


In [2]:
S = 16  
s2 = ''.join(random.choices(string.ascii_uppercase, k = S))    
s2= str(s2)
print("Second String: ",s2)

Second String:  FTTMSBYOLVEAWXRL


In [3]:
p ={'ma': 5, 'mi': -4, 'g': -1}
def mas(al, be):
    if al == be:
        return p['ma']
    elif al == '-' or be == '-':
        return p['g']
    else:
        return p['mi']
def DP(s1, s2):
    x, y,ms = len(s1), len(s2),0
    H = np.zeros((x+1, y+1))    
    T = np.zeros((x+1, y+1))
    for i in range(1, x + 1):
        for j in range(1, y + 1):
            sc_diag = H[i-1][j-1] + mas(s1[i-1], s2[j-1])
            sc_up = H[i][j-1] + p['g']
            sc_left = H[i-1][j] + p['g']
            H[i][j] = max(0,sc_left, sc_up, sc_diag)
            if H[i][j] == 0: T[i][j] = 0
            if H[i][j] == sc_left: T[i][j] = 1
            if H[i][j] == sc_up: T[i][j] = 2
            if H[i][j] == sc_diag: T[i][j] = 3
            if H[i][j] >= ms:
                m_i = i
                m_j = j
                ms = H[i][j];
    print('H=\n',H,'\n')
    al1, al2 = '', ''
    i,j = m_i,m_j
    
    
   
    while T[i][j] != 0:
        if T[i][j] == 3:
            a1 = s1[i-1]
            a2 = s2[j-1]
            i -= 1
            j -= 1
        elif T[i][j] == 2:
            a1 = '-'
            a2 = s2[j-1]
            j -= 1
        elif T[i][j] == 1:
            a1 = s1[i-1]
            a2 = '-'
            i -= 1
        print('a1 = %s\t a2 = %s\n' % (a1,a2))
        al1 += a1
        al2 += a2
    al1 = al1[::-1]
    al2 = al2[::-1]
    sym = ''
    for i in range(len(al1)):
        a1 = al1[i]
        a2 = al2[i]
        if a1 == a2:                
            sym += a1
        elif a1 != a2 and a1 != '-' and a2 != '-': 
            sym += ' '
        elif a1 == '-' or a2 == '-':          
            sym += ' '
    print('Score =', ms)
    print(al1)
    print(sym)
    print(al2)
DP(s1,s2)

H=
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 4. 3. 2. 1. 0. 0. 5.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 4. 3. 2. 1. 0. 0. 5.]
 [0. 0. 0. 0. 0. 0. 0. 0. 5. 4. 3. 2. 1. 0. 0. 0. 4.]
 [0. 0. 0. 0. 0. 0. 0. 0. 4. 3. 2. 1. 0. 0. 0. 0. 3.]
 [0. 0. 0. 0. 0. 0. 0. 0. 3. 2. 1. 0. 0. 0. 0. 0. 2.]
 [0. 0. 5. 5. 4. 3. 2. 1. 2. 1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 4. 4. 3. 2. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 3. 2. 1. 0. 6. 5. 4. 3. 2. 1. 0. 0. 0. 0.]
 [0. 0. 2. 2. 1. 0. 0. 5. 4. 3. 2. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 4. 3. 2. 8. 7. 6. 5. 4. 3. 2.]
 [0. 0. 0. 0. 0. 0. 0. 5. 4. 3. 7. 6. 5. 4. 3. 2. 1.]
 [0. 0. 0. 0. 0. 0. 0. 4. 3. 2. 6. 5. 4. 3. 9. 8. 7.]
 [0. 0. 0. 0. 0. 0. 0. 3. 2. 1. 5. 4. 3. 2. 8. 7. 6.]
 [0. 0. 0. 0. 0. 0. 0. 2. 1. 0. 4. 3. 2. 1. 7. 6. 5.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 3. 2. 1. 0. 6. 5. 4.]
 [0. 0. 0. 0. 0. 0. 0. 5. 4. 3. 2. 1. 0. 0. 5. 4. 3.]] 

a1 = X	 a2 = X

a1 = -	 a2 = W

a1 = -	 a2 = A

a1 = -	 a2 = E

a1 = Y	 a2 